version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/airline_db
      - DATABASE_NAME=airline_db
      - PORT=3000
    depends_on:
      - mongo
    volumes:
      - ./dataset:/app/dataset:ro
    networks:
      - airline-network

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - airline-network

networks:
  airline-network:
    driver: bridge

volumes:
  mongo-data: